version: '3.8'

services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:1234567890@postgres:5432/shop-fastapi
    volumes:
      - .:/app
      - /app/__pycache__
    ports:
      - "8000:8000"

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567890
      - POSTGRES_DB=shop-fastapi
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: